@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person_Ext(user1, "Architect", "架构师 / 架构办")
Person_Ext(user2, "Dev", "开发")

System_Boundary(c1, "ArchGuard Core") {
    Container(codeAnalysisFE, "Code Analysis F/E", "ArchGuard UI")
    Container(codeAnalysisModule, "Code Analysis", "Kotlin", "架构分析功能，如依赖分析、指标分析(只读DB)")
    Container(codeScanner, "Code Scanner", "Kotlin", "各级扫描调用入口（只写DB，不读）")
    Container(codeScanTools , "Code Scan Jars", "Kotlin", "具体扫描工具Jar包：Java依赖关系、PLSQL调用关系、代码复杂度、Jacoco报告、Git提交记录的扫描")
    Container(codeAnalysisAddition, "Code Addition", "Kotlin", "杂货铺：评估报告、PLSQL2Kt、多项目管理等（DB读写）")
  Container(jenkins, "Jenkins Image", "Docker","定制Jenkins镜像")
  Container(dependencyAnalyzerPlugin, "Dependency Analyzer Plugin", "Java", "Jenkins插件")
}

System_Boundary(c2, "ArchGuard Infrastructure") {
  Container(flywayService, "Flyway Service", "Support DB Auto upgrade")
  Container(documentApp, "Document App", "Swagger server for all B/E API")
  Container(eurekaServer, "EurekaServer", "Java", "EurekaServer")  
  Container(archguardDeploy, "Archguard Deploy", "Shell", "Deploy script")  
}


Rel(user1, codeAnalysisFE, "F/E UI", "JSON")
Rel(user2, codeAnalysisFE, "F/E UI", "JSON")
Rel(user2, jenkins, "Jenkins UI", "JSON")

Rel(codeAnalysisFE, codeAnalysisModule, "HTTP", "JSON")
Rel(codeAnalysisFE, codeScanner, "HTTP", "JSON")
Rel(codeAnalysisFE, codeAnalysisAddition, "HTTP", "JSON")
Rel(codeScanner, codeScanTools, "Jar", "Invoke")

Rel(dependencyAnalyzerPlugin, codeScanTools, "Jar", "Invoke")
Rel(dependencyAnalyzerPlugin, codeAnalysisModule, "HTTP", "JSON")
Rel(jenkins, dependencyAnalyzerPlugin, "Plugin", "Invoke")
@enduml
